version: "3.8"

services:
  rentx_db:
    image: postgres
    container_name: rentx_db
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=q1w2e3
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentx
    # ports:
    #   - 3333:3333
    #   - 9229:9229
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local